// <auto-generated />
using System;
using Masroo3k.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Masroo3k.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("InitialCreateSQLServer")]
    partial class InitialCreateSQLServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Masroo3k.Api.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("InitialCreateSQLServer");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InitialCreateSQLServer")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<int?>("EntityId")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<int?>("UserId")
                        .HasColumnType("InitialCreateSQLServer");

                    b.HasKey("Id");

                    b.HasIndex("InitialCreateSQLServer");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InitialCreateSQLServer");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("InitialCreateSQLServer");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InitialCreateSQLServer")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("ExecutiveSummary")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<decimal>("ExpectedROI")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<decimal>("InitialCreateSQLServer")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("KeyFindings")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<int>("OwnerId")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<int>("InitialCreateSQLServer")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<int>("SuccessPercent")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TemplateId");

                    b.ToTable("InitialCreateSQLServer");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("InitialCreateSQLServer");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<int>("UserId")
                        .HasColumnType("InitialCreateSQLServer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("UserId");

                    b.ToTable("InitialCreateSQLServer");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("InitialCreateSQLServer");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InitialCreateSQLServer")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .HasMaxLength(280)
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<int>("InitialCreateSQLServer")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("InitialCreateSQLServer");

                    b.HasKey("Id");

                    b.ToTable("InitialCreateSQLServer");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.TemplateField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("InitialCreateSQLServer");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("FieldOptions")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<int>("FieldOrder")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<int?>("MinLength")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<bool>("MustBeBetween0And100")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<bool>("MustBePositive")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<bool>("MustBeValidUrl")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<int>("StageNumber")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<int>("TemplateId")
                        .HasColumnType("InitialCreateSQLServer");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "StageNumber", "FieldOrder");

                    b.ToTable("TemplateFields");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("InitialCreateSQLServer");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.Property<string>("InitialCreateSQLServer")
                        .IsRequired()
                        .HasColumnType("InitialCreateSQLServer");

                    b.HasKey("Id");

                    b.HasIndex("InitialCreateSQLServer")
                        .IsUnique();

                    b.ToTable("InitialCreateSQLServer");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.ActivityLog", b =>
                {
                    b.HasOne("Masroo3k.Api.Models.User", "InitialCreateSQLServer")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InitialCreateSQLServer");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.Analysis", b =>
                {
                    b.HasOne("Masroo3k.Api.Models.User", "InitialCreateSQLServer")
                        .WithMany("InitialCreateSQLServer")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Masroo3k.Api.Models.Template", "InitialCreateSQLServer")
                        .WithMany("InitialCreateSQLServer")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InitialCreateSQLServer");

                    b.Navigation("InitialCreateSQLServer");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.Notification", b =>
                {
                    b.HasOne("Masroo3k.Api.Models.User", "InitialCreateSQLServer")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialCreateSQLServer");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.TemplateField", b =>
                {
                    b.HasOne("Masroo3k.Api.Models.Template", "InitialCreateSQLServer")
                        .WithMany("Fields")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitialCreateSQLServer");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.Template", b =>
                {
                    b.Navigation("InitialCreateSQLServer");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Masroo3k.Api.Models.User", b =>
                {
                    b.Navigation("InitialCreateSQLServer");
                });
#pragma warning restore 612, 618
        }
    }
}
